######################################################################
# Automatically generated by qmake (3.1) Mon Apr 24 22:27:21 2017
######################################################################

TEMPLATE = app
TARGET = Library
INCLUDEPATH += .

QT += core gui widgets

# Input
HEADERS += Book.h User.h BookManager.h BookStorage.h \
    libraryui.h
SOURCES += Book.cpp User.cpp BookManager.cpp BookStorage.cpp main.cpp \
    libraryui.cpp
